/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author juan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jpControlPanel = new javax.swing.JPanel();
        jControlpanel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setFocusTraversalPolicyProvider(true);

        jpControlPanel.setBackground(new java.awt.Color(153, 153, 153));
        jpControlPanel.setPreferredSize(new java.awt.Dimension(190, 500));
        jpControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jControlpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu (1).png"))); // NOI18N
        jControlpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jControlpanelMouseClicked(evt);
            }
        });
        jpControlPanel.add(jControlpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 15, 27));
        jLabel5.setText("Registrar visita");
        jpControlPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 15, 27));
        jLabel6.setText("Croquis");
        jpControlPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(110, 15, 27));
        jLabel7.setText("Factura");
        jpControlPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 15, 27));
        jLabel3.setText("Membresia");
        jpControlPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        jLabel38.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(110, 15, 27));
        jLabel38.setText("Residente");
        jpControlPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 40));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 15, 27));
        jLabel4.setText("Vivienda");
        jpControlPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario (8).png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpControlPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 40, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/factura-aprobada.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpControlPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mapa (1).png"))); // NOI18N
        jButton3.setToolTipText("");
        jpControlPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/factura.png"))); // NOI18N
        jButton4.setToolTipText("");
        jpControlPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 40, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tarjeta-de-visita-de-un-hombre-con-informacion-de-contacto.png"))); // NOI18N
        jButton5.setToolTipText("");
        jpControlPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/grupo-de-usuarios.png"))); // NOI18N
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jpControlPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/interfaz-de-hogar.png"))); // NOI18N
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jpControlPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jpControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jControlpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jControlpanelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jControlpanelMouseClicked
Vivienda v = new Vivienda(); Dueno d = new Dueno(); Fresidentes fr = new Fresidentes();
    public void limpiarformularios(){
        v.dispose(); d.dispose(); fr.dispose();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
   
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.limpiarformularios();
        d = new Dueno();this.jDesktopPane1.add(d);d.setVisible(true);d.setTitle("DUEÑOS");d.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.limpiarformularios();
        v = new Vivienda();
       this.jDesktopPane1.add(v);v.setVisible(true);v.show();
      int x =(this.jDesktopPane1.getWidth()/2)-v.getWidth()/2;
      int y =(this.jDesktopPane1.getWidth()/2)-v.getWidth()/2;
      v.setLocation(x,y);v.setTitle("VIVIENDAS");
        try{
       // v.setMaximum(true);
     
    }catch(Exception ex){}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.limpiarformularios();
        fr = new Fresidentes();this.jDesktopPane1.add(fr);d.setVisible(true);fr.setTitle("RESIDENTES");fr.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jControlpanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpControlPanel;
    // End of variables declaration//GEN-END:variables
}
